# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"H\n\x13InferenceParameters\x12\n\n\x02tx\x18\x01 \x01(\t\x12\x11\n\tmodelHash\x18\x02 \x01(\t\x12\x12\n\nmodelInput\x18\x03 \x01(\t\"k\n\x12PipelineParameters\x12\n\n\x02tx\x18\x01 \x01(\t\x12\x0c\n\x04seed\x18\x02 \x01(\t\x12\x14\n\x0cpipelineName\x18\x03 \x01(\t\x12\x11\n\tmodelHash\x18\x04 \x01(\t\x12\x12\n\nmodelInput\x18\x05 \x01(\t\":\n\x0fInferenceResult\x12\n\n\x02tx\x18\x01 \x01(\t\x12\x0c\n\x04node\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"v\n\x11ZKInferenceResult\x12\n\n\x02tx\x18\x01 \x01(\t\x12\x0c\n\x04node\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\r\n\x05proof\x18\x04 \x01(\t\x12\x10\n\x08settings\x18\x05 \x01(\t\x12\n\n\x02vk\x18\x06 \x01(\x0c\x12\x0b\n\x03srs\x18\x07 \x01(\t2\xf1\x01\n\tInference\x12J\n\x0cRunInference\x12\x1e.inference.InferenceParameters\x1a\x1a.inference.InferenceResult\x12N\n\x0eRunZKInference\x12\x1e.inference.InferenceParameters\x1a\x1c.inference.ZKInferenceResult\x12H\n\x0bRunPipeline\x12\x1d.inference.PipelineParameters\x1a\x1a.inference.InferenceResultB\x13\xaa\x02\x10inference_serverb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\020inference_server'
  _globals['_INFERENCEPARAMETERS']._serialized_start=30
  _globals['_INFERENCEPARAMETERS']._serialized_end=102
  _globals['_PIPELINEPARAMETERS']._serialized_start=104
  _globals['_PIPELINEPARAMETERS']._serialized_end=211
  _globals['_INFERENCERESULT']._serialized_start=213
  _globals['_INFERENCERESULT']._serialized_end=271
  _globals['_ZKINFERENCERESULT']._serialized_start=273
  _globals['_ZKINFERENCERESULT']._serialized_end=391
  _globals['_INFERENCE']._serialized_start=394
  _globals['_INFERENCE']._serialized_end=635
# @@protoc_insertion_point(module_scope)
