# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import zkinference_pb2 as zkinference__pb2


class ZKInferenceStub(object):
    """Inference service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunZKInference = channel.unary_unary(
                '/inference.ZKInference/RunZKInference',
                request_serializer=zkinference__pb2.InferenceParameters.SerializeToString,
                response_deserializer=zkinference__pb2.ZKInferenceResult.FromString,
                )


class ZKInferenceServicer(object):
    """Inference service definition
    """

    def RunZKInference(self, request, context):
        """Runs a model inference
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ZKInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunZKInference': grpc.unary_unary_rpc_method_handler(
                    servicer.RunZKInference,
                    request_deserializer=zkinference__pb2.InferenceParameters.FromString,
                    response_serializer=zkinference__pb2.ZKInferenceResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.ZKInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ZKInference(object):
    """Inference service definition
    """

    @staticmethod
    def RunZKInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inference.ZKInference/RunZKInference',
            zkinference__pb2.InferenceParameters.SerializeToString,
            zkinference__pb2.ZKInferenceResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
