# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zkinference.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11zkinference.proto\x12\tinference\"H\n\x13InferenceParameters\x12\n\n\x02tx\x18\x01 \x01(\t\x12\x11\n\tmodelHash\x18\x02 \x01(\t\x12\x12\n\nmodelInput\x18\x03 \x01(\t\"v\n\x11ZKInferenceResult\x12\n\n\x02tx\x18\x01 \x01(\t\x12\x0c\n\x04node\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\r\n\x05proof\x18\x04 \x01(\t\x12\x10\n\x08settings\x18\x05 \x01(\t\x12\n\n\x02vk\x18\x06 \x01(\x0c\x12\x0b\n\x03srs\x18\x07 \x01(\x0c\x32]\n\x0bZKInference\x12N\n\x0eRunZKInference\x12\x1e.inference.InferenceParameters\x1a\x1c.inference.ZKInferenceResultB\x13\xaa\x02\x10inference_serverb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zkinference_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\020inference_server'
  _globals['_INFERENCEPARAMETERS']._serialized_start=32
  _globals['_INFERENCEPARAMETERS']._serialized_end=104
  _globals['_ZKINFERENCERESULT']._serialized_start=106
  _globals['_ZKINFERENCERESULT']._serialized_end=224
  _globals['_ZKINFERENCE']._serialized_start=226
  _globals['_ZKINFERENCE']._serialized_end=319
# @@protoc_insertion_point(module_scope)
